version: "3.8"

services:
  streamlit-service:
    image: sample-streamlit
    container_name: streamlit-container
    command: streamlit run server.py

  nginx-service:
    image: nginx:alpine3.19
    container_name: nginx-container
    ports:
      - "${HTTPS_PORT}:443"
      # - "${HTTP_PORT}:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/certificate.crt:/etc/nginx/certs/certificate.crt
      - ./nginx/private-key.key:/etc/nginx/certs/private-key.key
    depends_on:
      - streamlit-service
